/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.AddRulesRequest
import fr.haan.open_api_playground_app.data.entities.DeleteRulesRequest
import fr.haan.open_api_playground_app.data.entities.DeleteRulesRequestDelete
import fr.haan.open_api_playground_app.data.entities.RuleNoId

import com.squareup.moshi.Json

/**
 * 
 *
 * @param add 
 * @param delete 
 */

data class AddOrDeleteRulesRequest (

    @Json(name = "add")
    val add: kotlin.collections.List<RuleNoId>,

    @Json(name = "delete")
    val delete: DeleteRulesRequestDelete

)

