/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.BookmarkMutationResponseData
import fr.haan.open_api_playground_app.data.entities.Problem

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param errors 
 */

data class BookmarkMutationResponse (

    @Json(name = "data")
    val `data`: BookmarkMutationResponseData? = null,

    @Json(name = "errors")
    val errors: kotlin.collections.List<Problem>? = null

)

