/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.ClientForbiddenProblemAllOf
import fr.haan.open_api_playground_app.data.entities.Problem

import com.squareup.moshi.Json

/**
 * A problem that indicates your client is forbidden from making this request.
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 * @param reason 
 * @param registrationUrl 
 */

data class ClientForbiddenProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null,

    @Json(name = "reason")
    val reason: ClientForbiddenProblem.Reason? = null,

    @Json(name = "registration_url")
    val registrationUrl: java.net.URI? = null

) : Problem() {

    /**
     * 
     *
     * Values: officialMinusClientMinusForbidden,clientMinusNotMinusEnrolled
     */
    enum class Reason(val value: kotlin.String) {
        @Json(name = "official-client-forbidden") officialMinusClientMinusForbidden("official-client-forbidden"),
        @Json(name = "client-not-enrolled") clientMinusNotMinusEnrolled("client-not-enrolled");
    }
}

