/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * @param connectionIssue 
 */

data class ConnectionExceptionProblemAllOf (

    @Json(name = "connection_issue")
    val connectionIssue: ConnectionExceptionProblemAllOf.ConnectionIssue? = null

) {

    /**
     * 
     *
     * Values: tooManyConnections,provisioningSubscription,ruleConfigurationIssue,rulesInvalidIssue
     */
    enum class ConnectionIssue(val value: kotlin.String) {
        @Json(name = "TooManyConnections") tooManyConnections("TooManyConnections"),
        @Json(name = "ProvisioningSubscription") provisioningSubscription("ProvisioningSubscription"),
        @Json(name = "RuleConfigurationIssue") ruleConfigurationIssue("RuleConfigurationIssue"),
        @Json(name = "RulesInvalidIssue") rulesInvalidIssue("RulesInvalidIssue");
    }
}

