/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * Represents the data for the context annotation domain.
 *
 * @param id The unique id for a context annotation domain.
 * @param name Name of the context annotation domain.
 * @param description Description of the context annotation domain.
 */

data class ContextAnnotationDomainFields (

    /* The unique id for a context annotation domain. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Name of the context annotation domain. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Description of the context annotation domain. */
    @Json(name = "description")
    val description: kotlin.String? = null

)

