/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.DuplicateRuleProblemAllOf
import fr.haan.open_api_playground_app.data.entities.Problem

import com.squareup.moshi.Json

/**
 * The rule you have submitted is a duplicate.
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 * @param `value` 
 * @param id 
 */

data class DuplicateRuleProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null

) : Problem()

