/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Media
import fr.haan.open_api_playground_app.data.entities.Place
import fr.haan.open_api_playground_app.data.entities.Poll
import fr.haan.open_api_playground_app.data.entities.Tweet
import fr.haan.open_api_playground_app.data.entities.User

import com.squareup.moshi.Json

/**
 * 
 *
 * @param users 
 * @param tweets 
 * @param places 
 * @param media 
 * @param polls 
 */

data class Expansions (

    @Json(name = "users")
    val users: kotlin.collections.List<User>? = null,

    @Json(name = "tweets")
    val tweets: kotlin.collections.List<Tweet>? = null,

    @Json(name = "places")
    val places: kotlin.collections.List<Place>? = null,

    @Json(name = "media")
    val media: kotlin.collections.List<Media>? = null,

    @Json(name = "polls")
    val polls: kotlin.collections.List<Poll>? = null

)

