/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.FieldUnauthorizedProblemAllOf
import fr.haan.open_api_playground_app.data.entities.Problem

import com.squareup.moshi.Json

/**
 * A problem that indicates that you are not allowed to see a particular field on a Tweet, User, etc.
 *
 * @param type 
 * @param title 
 * @param section 
 * @param resourceType 
 * @param `field` 
 * @param detail 
 * @param status 
 */

data class FieldUnauthorizedProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "section")
    val section: FieldUnauthorizedProblem.Section,

    @Json(name = "resource_type")
    val resourceType: FieldUnauthorizedProblem.ResourceType,

    @Json(name = "field")
    val `field`: kotlin.String,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null

) : Problem() {

    /**
     * 
     *
     * Values: `data`,includes
     */
    enum class Section(val value: kotlin.String) {
        @Json(name = "data") `data`("data"),
        @Json(name = "includes") includes("includes");
    }
    /**
     * 
     *
     * Values: tweet,user,media,list,space
     */
    enum class ResourceType(val value: kotlin.String) {
        @Json(name = "tweet") tweet("tweet"),
        @Json(name = "user") user("user"),
        @Json(name = "media") media("media"),
        @Json(name = "list") list("list"),
        @Json(name = "space") space("space");
    }
}

