/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Expansions
import fr.haan.open_api_playground_app.data.entities.FilteredStreamingTweetOneOfMatchingRules
import fr.haan.open_api_playground_app.data.entities.Tweet

import com.squareup.moshi.Json

/**
 * The values returned with a successful streamed tweet. Includes the user provided rules that the tweet matched.
 *
 * @param `data` 
 * @param matchingRules The list of rules which matched the tweet
 * @param includes 
 */

data class FilteredStreamingTweetOneOf (

    @Json(name = "data")
    val `data`: Tweet,

    /* The list of rules which matched the tweet */
    @Json(name = "matching_rules")
    val matchingRules: kotlin.collections.List<FilteredStreamingTweetOneOfMatchingRules>,

    @Json(name = "includes")
    val includes: Expansions? = null

)

