/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * @param newestId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param oldestId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param previousToken The previous token
 * @param nextToken The next token
 * @param resultCount Number of Tweets in result set
 */

data class GenericTweetsTimelineResponseMeta (

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @Json(name = "newest_id")
    val newestId: kotlin.String? = null,

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @Json(name = "oldest_id")
    val oldestId: kotlin.String? = null,

    /* The previous token */
    @Json(name = "previous_token")
    val previousToken: kotlin.String? = null,

    /* The next token */
    @Json(name = "next_token")
    val nextToken: kotlin.String? = null,

    /* Number of Tweets in result set */
    @Json(name = "result_count")
    val resultCount: kotlin.Int? = null

)

