/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.ComplianceJobType

import com.squareup.moshi.Json

/**
 * A request to create a new batch compliance job.
 *
 * @param type 
 * @param resumable If true, this endpoint will return a pre-signed URL with resumable uploads enabled
 * @param name User-provided name for a compliance job
 */

data class InlineObject5 (

    @Json(name = "type")
    val type: ComplianceJobType,

    /* If true, this endpoint will return a pre-signed URL with resumable uploads enabled */
    @Json(name = "resumable")
    val resumable: kotlin.Boolean? = null,

    /* User-provided name for a compliance job */
    @Json(name = "name")
    val name: kotlin.String? = null

)

