/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Model2TweetsGeo
import fr.haan.open_api_playground_app.data.entities.Model2TweetsMedia
import fr.haan.open_api_playground_app.data.entities.Model2TweetsPoll
import fr.haan.open_api_playground_app.data.entities.Model2TweetsReply

import com.squareup.moshi.Json

/**
 * 
 *
 * @param text The content of the Tweet.
 * @param directMessageDeepLink Link to take the conversation from the public timeline to a private Direct Message.
 * @param quoteTweetId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param forSuperFollowersOnly Exclusive Tweet for super followers.
 * @param reply 
 * @param media 
 * @param poll 
 * @param replySettings Settings to indicate who can reply to the Tweet.
 * @param geo 
 */

data class InlineObject3 (

    /* The content of the Tweet. */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* Link to take the conversation from the public timeline to a private Direct Message. */
    @Json(name = "direct_message_deep_link")
    val directMessageDeepLink: kotlin.String? = null,

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @Json(name = "quote_tweet_id")
    val quoteTweetId: kotlin.String? = null,

    /* Exclusive Tweet for super followers. */
    @Json(name = "for_super_followers_only")
    val forSuperFollowersOnly: kotlin.Boolean? = null,

    @Json(name = "reply")
    val reply: Model2TweetsReply? = null,

    @Json(name = "media")
    val media: Model2TweetsMedia? = null,

    @Json(name = "poll")
    val poll: Model2TweetsPoll? = null,

    /* Settings to indicate who can reply to the Tweet. */
    @Json(name = "reply_settings")
    val replySettings: InlineObject3.ReplySettings? = null,

    @Json(name = "geo")
    val geo: Model2TweetsGeo? = null

) {

    /**
     * Settings to indicate who can reply to the Tweet.
     *
     * Values: following,mentionedUsers
     */
    enum class ReplySettings(val value: kotlin.String) {
        @Json(name = "following") following("following"),
        @Json(name = "mentionedUsers") mentionedUsers("mentionedUsers");
    }
}

