/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * @param disconnectType 
 */

data class OperationalDisconnectProblemAllOf (

    @Json(name = "disconnect_type")
    val disconnectType: OperationalDisconnectProblemAllOf.DisconnectType? = null

) {

    /**
     * 
     *
     * Values: operationalDisconnect,upstreamOperationalDisconnect,forceDisconnect,upstreamUncleanDisconnect,slowReader,internalError,clientApplicationStateDegraded,invalidRules
     */
    enum class DisconnectType(val value: kotlin.String) {
        @Json(name = "OperationalDisconnect") operationalDisconnect("OperationalDisconnect"),
        @Json(name = "UpstreamOperationalDisconnect") upstreamOperationalDisconnect("UpstreamOperationalDisconnect"),
        @Json(name = "ForceDisconnect") forceDisconnect("ForceDisconnect"),
        @Json(name = "UpstreamUncleanDisconnect") upstreamUncleanDisconnect("UpstreamUncleanDisconnect"),
        @Json(name = "SlowReader") slowReader("SlowReader"),
        @Json(name = "InternalError") internalError("InternalError"),
        @Json(name = "ClientApplicationStateDegraded") clientApplicationStateDegraded("ClientApplicationStateDegraded"),
        @Json(name = "InvalidRules") invalidRules("InvalidRules");
    }
}

