/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * Values: poi,neighborhood,city,admin,country,unknown
 */

enum class PlaceType(val value: kotlin.String) {

    @Json(name = "poi")
    poi("poi"),

    @Json(name = "neighborhood")
    neighborhood("neighborhood"),

    @Json(name = "city")
    city("city"),

    @Json(name = "admin")
    admin("admin"),

    @Json(name = "country")
    country("country"),

    @Json(name = "unknown")
    unknown("unknown");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PlaceType) "$data" else null

        /**
         * Returns a valid [PlaceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PlaceType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

