/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * @param nextToken This value is used to get the next 'page' of results by providing it to the pagination_token parameter.
 * @param resultCount The number of quoting tweets returned in this response
 */

data class QuoteTweetLookupResponseMeta (

    /* This value is used to get the next 'page' of results by providing it to the pagination_token parameter. */
    @Json(name = "next_token")
    val nextToken: kotlin.String? = null,

    /* The number of quoting tweets returned in this response */
    @Json(name = "result_count")
    val resultCount: kotlin.Int? = null

)

