/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Problem
import fr.haan.open_api_playground_app.data.entities.ResourceNotFoundProblemAllOf

import com.squareup.moshi.Json

/**
 * A problem that indicates that a given Tweet, User, etc. does not exist.
 *
 * @param type 
 * @param title 
 * @param parameter 
 * @param `value` Value will match the schema of the field.
 * @param resourceId 
 * @param resourceType 
 * @param detail 
 * @param status 
 */

data class ResourceNotFoundProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "parameter")
    val parameter: kotlin.String,

    /* Value will match the schema of the field. */
    @Json(name = "value")
    val `value`: kotlin.Any?,

    @Json(name = "resource_id")
    val resourceId: kotlin.String,

    @Json(name = "resource_type")
    val resourceType: ResourceNotFoundProblem.ResourceType,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null

) : Problem {

    /**
     * 
     *
     * Values: user,tweet,media,list,space
     */
    enum class ResourceType(val value: kotlin.String) {
        @Json(name = "user") user("user"),
        @Json(name = "tweet") tweet("tweet"),
        @Json(name = "media") media("media"),
        @Json(name = "list") list("list"),
        @Json(name = "space") space("space");
    }
}

