/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Expansions
import fr.haan.open_api_playground_app.data.entities.Problem
import fr.haan.open_api_playground_app.data.entities.Space

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `data` 
 * @param includes 
 * @param errors 
 */

data class SingleSpaceLookupResponse (

    @Json(name = "data")
    val `data`: Space? = null,

    @Json(name = "includes")
    val includes: Expansions? = null,

    @Json(name = "errors")
    val errors: kotlin.collections.List<Problem>? = null

)

