/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.Point

import com.squareup.moshi.Json

/**
 * The location tagged on the Tweet, if the user provided one.
 *
 * @param coordinates 
 * @param placeId The identifier for this place
 */

data class TweetGeo (

    @Json(name = "coordinates")
    val coordinates: Point? = null,

    /* The identifier for this place */
    @Json(name = "place_id")
    val placeId: kotlin.String? = null

)

