/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import com.squareup.moshi.Json

/**
 * 
 *
 * @param following 
 * @param pendingFollow 
 */

data class UsersFollowingCreateResponseData (

    @Json(name = "following")
    val following: kotlin.Boolean? = null,

    @Json(name = "pending_follow")
    val pendingFollow: kotlin.Boolean? = null

)

