/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.VideoAllOfVariantsEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param previewImageUrl 
 * @param variants An array of all available variants of the media
 */
@Serializable
data class AnimatedGifAllOfEntity (

    @Contextual @SerialName(value = "preview_image_url")
    val previewImageUrl: java.net.URI? = null,

    /* An array of all available variants of the media */
    @SerialName(value = "variants")
    val variants: kotlin.collections.List<VideoAllOfVariantsEntity>? = null

)

