/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.ContextAnnotationDomainFieldsEntity
import fr.haan.open_api_playground_app.data.entities.ContextAnnotationEntityFieldsEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Annotation inferred from the tweet text.
 *
 * @param domain 
 * @param entity 
 */
@Serializable
data class ContextAnnotationEntity (

    @SerialName(value = "domain")
    val domain: ContextAnnotationDomainFieldsEntity,

    @SerialName(value = "entity")
    val entity: ContextAnnotationEntityFieldsEntity

)

