/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * IDs and values of all deleted user-specified stream filtering rules.
 *
 * @param ids IDs of all deleted user-specified stream filtering rules.
 * @param propertyValues Values of all deleted user-specified stream filtering rules.
 */
@Serializable
data class DeleteRulesRequestDeleteEntity (

    /* IDs of all deleted user-specified stream filtering rules. */
    @SerialName(value = "ids")
    val ids: kotlin.collections.List<kotlin.String>? = null,

    /* Values of all deleted user-specified stream filtering rules. */
    @SerialName(value = "values")
    val propertyValues: kotlin.collections.List<kotlin.String>? = null

)

