/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.MediaEntity
import fr.haan.open_api_playground_app.data.entities.PlaceEntity
import fr.haan.open_api_playground_app.data.entities.PollEntity
import fr.haan.open_api_playground_app.data.entities.TweetEntity
import fr.haan.open_api_playground_app.data.entities.UserEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param users 
 * @param tweets 
 * @param places 
 * @param media 
 * @param polls 
 */
@Serializable
data class ExpansionsEntity (

    @SerialName(value = "users")
    val users: kotlin.collections.List<UserEntity>? = null,

    @SerialName(value = "tweets")
    val tweets: kotlin.collections.List<TweetEntity>? = null,

    @SerialName(value = "places")
    val places: kotlin.collections.List<PlaceEntity>? = null,

    @SerialName(value = "media")
    val media: kotlin.collections.List<MediaEntity>? = null,

    @SerialName(value = "polls")
    val polls: kotlin.collections.List<PollEntity>? = null

)

