/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.PointEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param bbox 
 * @param properties 
 * @param geometry 
 */
@Serializable
data class GeoEntity (

    @SerialName(value = "type")
    val type: GeoEntity.Type,

    @SerialName(value = "bbox")
    val bbox: kotlin.collections.List<kotlin.Double>,

    @Contextual @SerialName(value = "properties")
    val properties: kotlin.Any,

    @SerialName(value = "geometry")
    val geometry: PointEntity? = null

) {

    /**
     * 
     *
     * Values: feature
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Feature") feature("Feature");
    }
}

