/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represent the portion of text recognized as a Hashtag, and its start and end position within the text.
 *
 * @param tag The text of the Hashtag
 */
@Serializable
data class HashtagFieldsEntity (

    /* The text of the Hashtag */
    @SerialName(value = "tag")
    val tag: kotlin.String

)

