/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param previousToken The previous token
 * @param nextToken The next token
 * @param resultCount Number of Tweets in result set
 */
@Serializable
data class InlineResponse2002MetaEntity (

    /* The previous token */
    @SerialName(value = "previous_token")
    val previousToken: kotlin.String? = null,

    /* The next token */
    @SerialName(value = "next_token")
    val nextToken: kotlin.String? = null,

    /* Number of Tweets in result set */
    @SerialName(value = "result_count")
    val resultCount: kotlin.Int? = null

)

