/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.ComplianceJobTypeEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A request to create a new batch compliance job.
 *
 * @param type 
 * @param resumable If true, this endpoint will return a pre-signed URL with resumable uploads enabled
 * @param name User-provided name for a compliance job
 */
@Serializable
data class InlineObject5Entity (

    @Contextual @SerialName(value = "type")
    val type: ComplianceJobTypeEntity,

    /* If true, this endpoint will return a pre-signed URL with resumable uploads enabled */
    @SerialName(value = "resumable")
    val resumable: kotlin.Boolean? = null,

    /* User-provided name for a compliance job */
    @SerialName(value = "name")
    val name: kotlin.String? = null

)

