/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.EntityIndicesInclusiveExclusiveEntity
import fr.haan.open_api_playground_app.data.entities.MentionFieldsEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param start Index (zero-based) at which position this entity starts.  The index is inclusive.
 * @param end Index (zero-based) at which position this entity ends.  The index is exclusive.
 * @param username The Twitter handle (screen name) of this user.
 * @param id Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 */
@Serializable
data class MentionEntityEntity (

    /* Index (zero-based) at which position this entity starts.  The index is inclusive. */
    @SerialName(value = "start")
    val start: kotlin.Int,

    /* Index (zero-based) at which position this entity ends.  The index is exclusive. */
    @SerialName(value = "end")
    val end: kotlin.Int,

    /* The Twitter handle (screen name) of this user. */
    @SerialName(value = "username")
    val username: kotlin.String,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "id")
    val id: kotlin.String

)

