/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A [GeoJson Point](https://tools.ietf.org/html/rfc7946#section-3.1.2) geometry object.
 *
 * @param type 
 * @param coordinates A [GeoJson Position](https://tools.ietf.org/html/rfc7946#section-3.1.1) in the format `[longitude,latitude]`.
 */
@Serializable
data class PointEntity (

    @SerialName(value = "type")
    val type: PointEntity.Type,

    /* A [GeoJson Position](https://tools.ietf.org/html/rfc7946#section-3.1.1) in the format `[longitude,latitude]`. */
    @SerialName(value = "coordinates")
    val coordinates: kotlin.collections.List<@Contextual java.math.BigDecimal>

) {

    /**
     * 
     *
     * Values: point
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Point") point("Point");
    }
}

