/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.PollOptionEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represent a Poll attached to a Tweet
 *
 * @param id Unique identifier of this poll.
 * @param options 
 * @param votingStatus 
 * @param endDatetime 
 * @param durationMinutes 
 */
@Serializable
data class PollEntity (

    /* Unique identifier of this poll. */
    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "options")
    val options: kotlin.collections.List<PollOptionEntity>,

    @SerialName(value = "voting_status")
    val votingStatus: PollEntity.VotingStatus? = null,

    @Contextual @SerialName(value = "end_datetime")
    val endDatetime: java.time.OffsetDateTime? = null,

    @SerialName(value = "duration_minutes")
    val durationMinutes: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: `open`,closed
     */
    @Serializable
    enum class VotingStatus(val value: kotlin.String) {
        @SerialName(value = "open") `open`("open"),
        @SerialName(value = "closed") closed("closed");
    }
}

