/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Describes a choice in a Poll object.
 *
 * @param position Position of this choice in the poll.
 * @param label The text of a poll choice.
 * @param votes Number of users who voted for this choice.
 */
@Serializable
data class PollOptionEntity (

    /* Position of this choice in the poll. */
    @SerialName(value = "position")
    val position: kotlin.Int,

    /* The text of a poll choice. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Number of users who voted for this choice. */
    @SerialName(value = "votes")
    val votes: kotlin.Int

)

