/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 */
@Serializable
interface ProblemEntity {

    @SerialName(value = "type")
    val type: kotlin.String
    @SerialName(value = "title")
    val title: kotlin.String
    @SerialName(value = "detail")
    val detail: kotlin.String?
    @SerialName(value = "status")
    val status: kotlin.Int?
}

