/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param parameter 
 * @param `value` Value will match the schema of the field.
 * @param resourceId 
 * @param resourceType 
 */
@Serializable
data class ResourceNotFoundProblemAllOfEntity (

    @SerialName(value = "parameter")
    val parameter: kotlin.String,

    /* Value will match the schema of the field. */
    @Contextual @SerialName(value = "value")
    val `value`: kotlin.Any?,

    @SerialName(value = "resource_id")
    val resourceId: kotlin.String,

    @SerialName(value = "resource_type")
    val resourceType: ResourceNotFoundProblemAllOfEntity.ResourceType

) {

    /**
     * 
     *
     * Values: user,tweet,media,list,space
     */
    @Serializable
    enum class ResourceType(val value: kotlin.String) {
        @SerialName(value = "user") user("user"),
        @SerialName(value = "tweet") tweet("tweet"),
        @SerialName(value = "media") media("media"),
        @SerialName(value = "list") list("list"),
        @SerialName(value = "space") space("space");
    }
}

