/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.ProblemEntity
import fr.haan.open_api_playground_app.data.entities.ResourceNotFoundProblemAllOfEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A problem that indicates that a given Tweet, User, etc. does not exist.
 *
 * @param type 
 * @param title 
 * @param parameter 
 * @param `value` Value will match the schema of the field.
 * @param resourceId 
 * @param resourceType 
 * @param detail 
 * @param status 
 */
@Serializable
data class ResourceNotFoundProblemEntity (

    @SerialName(value = "type")
    override val type: kotlin.String,

    @SerialName(value = "title")
    override val title: kotlin.String,

    @SerialName(value = "parameter")
    val parameter: kotlin.String,

    /* Value will match the schema of the field. */
    @Contextual @SerialName(value = "value")
    val `value`: kotlin.Any?,

    @SerialName(value = "resource_id")
    val resourceId: kotlin.String,

    @SerialName(value = "resource_type")
    val resourceType: ResourceNotFoundProblemEntity.ResourceType,

    @SerialName(value = "detail")
    override val detail: kotlin.String? = null,

    @SerialName(value = "status")
    override val status: kotlin.Int? = null

) : ProblemEntity {

    /**
     * 
     *
     * Values: user,tweet,media,list,space
     */
    @Serializable
    enum class ResourceType(val value: kotlin.String) {
        @SerialName(value = "user") user("user"),
        @SerialName(value = "tweet") tweet("tweet"),
        @SerialName(value = "media") media("media"),
        @SerialName(value = "list") list("list"),
        @SerialName(value = "space") space("space");
    }
}

