/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represent a Search Count Result
 *
 * @param end The end time of the bucket
 * @param start The start time of the bucket
 * @param tweetCount The count for the bucket
 */
@Serializable
data class SearchCountEntity (

    /* The end time of the bucket */
    @Contextual @SerialName(value = "end")
    val end: java.time.OffsetDateTime,

    /* The start time of the bucket */
    @Contextual @SerialName(value = "start")
    val start: java.time.OffsetDateTime,

    /* The count for the bucket */
    @SerialName(value = "tweet_count")
    val tweetCount: kotlin.Int

)

