/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param id Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 */
@Serializable
data class TweetReferencedTweetsEntity (

    @SerialName(value = "type")
    val type: TweetReferencedTweetsEntity.Type,

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "id")
    val id: kotlin.String

) {

    /**
     * 
     *
     * Values: retweeted,quoted,repliedTo
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "retweeted") retweeted("retweeted"),
        @SerialName(value = "quoted") quoted("quoted"),
        @SerialName(value = "replied_to") repliedTo("replied_to");
    }
}

