/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
 *
 * @param copyright Indicates if the content is being withheld for on the basis of copyright infringement.
 * @param countryCodes Provides a list of countries where this content is not available.
 * @param scope Indicates whether the content being withheld is the `tweet` or a `user`.
 */
@Serializable
data class TweetWithheldEntity (

    /* Indicates if the content is being withheld for on the basis of copyright infringement. */
    @SerialName(value = "copyright")
    val copyright: kotlin.Boolean,

    /* Provides a list of countries where this content is not available. */
    @SerialName(value = "country_codes")
    val countryCodes: kotlin.collections.List<kotlin.String>,

    /* Indicates whether the content being withheld is the `tweet` or a `user`. */
    @SerialName(value = "scope")
    val scope: TweetWithheldEntity.Scope? = null

) {

    /**
     * Indicates whether the content being withheld is the `tweet` or a `user`.
     *
     * Values: tweet,user
     */
    @Serializable
    enum class Scope(val value: kotlin.String) {
        @SerialName(value = "tweet") tweet("tweet"),
        @SerialName(value = "user") user("user");
    }
}

