/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities

import fr.haan.open_api_playground_app.data.entities.URLImageEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represent the portion of text recognized as a URL.
 *
 * @param url A validly formatted URL.
 * @param expandedUrl A validly formatted URL.
 * @param displayUrl The URL as displayed in the Twitter client.
 * @param unwoundUrl Fully resolved url
 * @param status HTTP Status Code.
 * @param title Title of the page the URL points to.
 * @param description Description of the URL landing page.
 * @param images 
 * @param mediaKey The Media Key identifier for this attachment.
 */
@Serializable
data class URLFieldsEntity (

    /* A validly formatted URL. */
    @Contextual @SerialName(value = "url")
    val url: java.net.URI,

    /* A validly formatted URL. */
    @Contextual @SerialName(value = "expanded_url")
    val expandedUrl: java.net.URI? = null,

    /* The URL as displayed in the Twitter client. */
    @SerialName(value = "display_url")
    val displayUrl: kotlin.String? = null,

    /* Fully resolved url */
    @Contextual @SerialName(value = "unwound_url")
    val unwoundUrl: java.net.URI? = null,

    /* HTTP Status Code. */
    @SerialName(value = "status")
    val status: kotlin.Int? = null,

    /* Title of the page the URL points to. */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* Description of the URL landing page. */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "images")
    val images: kotlin.collections.List<URLImageEntity>? = null,

    /* The Media Key identifier for this attachment. */
    @SerialName(value = "media_key")
    val mediaKey: kotlin.String? = null

)

