/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.open_api_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Engagement metrics for the Media at the time of the request.
 *
 * @param viewCount Number of times this video has been viewed.
 */
@Serializable
data class VideoAllOfPublicMetricsEntity (

    /* Number of times this video has been viewed. */
    @SerialName(value = "view_count")
    val viewCount: kotlin.Int? = null

)

