/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddRulesRequest
import org.openapitools.client.models.DeleteRulesRequest
import org.openapitools.client.models.DeleteRulesRequestDelete
import org.openapitools.client.models.RuleNoId

import com.squareup.moshi.Json

/**
 * 
 *
 * @param add 
 * @param delete 
 */

data class AddOrDeleteRulesRequest (

    @Json(name = "add")
    val add: kotlin.collections.List<RuleNoId>,

    @Json(name = "delete")
    val delete: DeleteRulesRequestDelete

)

