/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ContextAnnotationDomainFields
import org.openapitools.client.models.ContextAnnotationEntityFields

import com.squareup.moshi.Json

/**
 * Annotation inferred from the tweet text.
 *
 * @param domain 
 * @param entity 
 */

data class ContextAnnotation (

    @Json(name = "domain")
    val domain: ContextAnnotationDomainFields,

    @Json(name = "entity")
    val entity: ContextAnnotationEntityFields

)

