/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeleteRulesRequestDelete

import com.squareup.moshi.Json

/**
 * A response from deleting user-specified stream filtering rules.
 *
 * @param delete 
 */

data class DeleteRulesRequest (

    @Json(name = "delete")
    val delete: DeleteRulesRequestDelete

)

