/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Expansions
import org.openapitools.client.models.FilteredStreamingTweetOneOf
import org.openapitools.client.models.FilteredStreamingTweetOneOf1
import org.openapitools.client.models.FilteredStreamingTweetOneOfMatchingRules
import org.openapitools.client.models.Problem
import org.openapitools.client.models.Tweet

import com.squareup.moshi.Json

/**
 * A tweet or error that can be returned by the streaming tweet API
 *
 * @param `data` 
 * @param matchingRules The list of rules which matched the tweet
 * @param errors 
 * @param includes 
 */

data class FilteredStreamingTweet (

    @Json(name = "data")
    val `data`: Tweet,

    /* The list of rules which matched the tweet */
    @Json(name = "matching_rules")
    val matchingRules: kotlin.collections.List<FilteredStreamingTweetOneOfMatchingRules>,

    @Json(name = "errors")
    val errors: kotlin.collections.List<Problem>,

    @Json(name = "includes")
    val includes: Expansions? = null

)

