/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param mediaKey The Media Key identifier for this attachment.
 * @param height The height of the media in pixels
 * @param width The width of the media in pixels
 */

interface Media {

    @Json(name = "type")
    val type: kotlin.String
    /* The Media Key identifier for this attachment. */
    @Json(name = "media_key")
    val mediaKey: kotlin.String?
    /* The height of the media in pixels */
    @Json(name = "height")
    val height: kotlin.Int?
    /* The width of the media in pixels */
    @Json(name = "width")
    val width: kotlin.Int?
}

