/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EntityIndicesInclusiveExclusive
import org.openapitools.client.models.MentionFields

import com.squareup.moshi.Json

/**
 * 
 *
 * @param start Index (zero-based) at which position this entity starts.  The index is inclusive.
 * @param end Index (zero-based) at which position this entity ends.  The index is exclusive.
 * @param username The Twitter handle (screen name) of this user.
 * @param id Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 */

data class MentionEntity (

    /* Index (zero-based) at which position this entity starts.  The index is inclusive. */
    @Json(name = "start")
    val start: kotlin.Int,

    /* Index (zero-based) at which position this entity ends.  The index is exclusive. */
    @Json(name = "end")
    val end: kotlin.Int,

    /* The Twitter handle (screen name) of this user. */
    @Json(name = "username")
    val username: kotlin.String,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @Json(name = "id")
    val id: kotlin.String

)

