/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Geo
import org.openapitools.client.models.PlaceType

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The identifier for this place
 * @param fullName The full name of this place.
 * @param name The human readable name of this place.
 * @param countryCode A two-letter ISO 3166-1 alpha-2 country code
 * @param placeType 
 * @param country The full name of the county in which this place exists.
 * @param containedWithin 
 * @param geo 
 */

data class Place (

    /* The identifier for this place */
    @Json(name = "id")
    val id: kotlin.String,

    /* The full name of this place. */
    @Json(name = "full_name")
    val fullName: kotlin.String,

    /* The human readable name of this place. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* A two-letter ISO 3166-1 alpha-2 country code */
    @Json(name = "country_code")
    val countryCode: kotlin.String? = null,

    @Json(name = "place_type")
    val placeType: PlaceType? = null,

    /* The full name of the county in which this place exists. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    @Json(name = "contained_within")
    val containedWithin: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "geo")
    val geo: Geo? = null

)

