/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param deleted Number of user-specified stream filtering rules that were deleted.
 * @param notDeleted Number of user-specified stream filtering rules that were not deleted.
 */

data class RulesRequestSummaryOneOf1 (

    /* Number of user-specified stream filtering rules that were deleted. */
    @Json(name = "deleted")
    val deleted: kotlin.Int,

    /* Number of user-specified stream filtering rules that were not deleted. */
    @Json(name = "not_deleted")
    val notDeleted: kotlin.Int

)

