/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Nonpublic engagement metrics for the Tweet at the time of the request.
 *
 * @param impressionCount Number of times this Tweet has been viewed.
 */

data class TweetNonPublicMetrics (

    /* Number of times this Tweet has been viewed. */
    @Json(name = "impression_count")
    val impressionCount: kotlin.Int? = null

)

