/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Represent the information for the URL image
 *
 * @param url A validly formatted URL.
 * @param height The height of the media in pixels
 * @param width The width of the media in pixels
 */

data class URLImage (

    /* A validly formatted URL. */
    @Json(name = "url")
    val url: java.net.URI? = null,

    /* The height of the media in pixels */
    @Json(name = "height")
    val height: kotlin.Int? = null,

    /* The width of the media in pixels */
    @Json(name = "width")
    val width: kotlin.Int? = null

)

