/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Indicates withholding details for [withheld content](https://help.twitter.com/en/rules-and-policies/tweet-withheld-by-country).
 *
 * @param countryCodes Provides a list of countries where this content is not available.
 * @param scope Indicates that the content being withheld is a `user`.
 */

data class UserWithheld (

    /* Provides a list of countries where this content is not available. */
    @Json(name = "country_codes")
    val countryCodes: kotlin.collections.List<kotlin.String>,

    /* Indicates that the content being withheld is a `user`. */
    @Json(name = "scope")
    val scope: UserWithheld.Scope? = null

) {

    /**
     * Indicates that the content being withheld is a `user`.
     *
     * Values: user
     */
    enum class Scope(val value: kotlin.String) {
        @Json(name = "user") user("user");
    }
}

