/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Engagement metrics for the Media at the time of the request.
 *
 * @param viewCount Number of times this video has been viewed.
 */

data class VideoAllOfPublicMetrics (

    /* Number of times this video has been viewed. */
    @Json(name = "view_count")
    val viewCount: kotlin.Int? = null

)

