/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Nonpublic engagement metrics for the Media at the time of the request.
 *
 * @param playback0Count Number of users who made it through 0% of the video.
 * @param playback25Count Number of users who made it through 25% of the video.
 * @param playback50Count Number of users who made it through 50% of the video.
 * @param playback75Count Number of users who made it through 75% of the video.
 * @param playback100Count Number of users who made it through 100% of the video.
 */

data class VideoAllOfNonPublicMetrics (

    /* Number of users who made it through 0% of the video. */
    @Json(name = "playback_0_count")
    val playback0Count: kotlin.Int? = null,

    /* Number of users who made it through 25% of the video. */
    @Json(name = "playback_25_count")
    val playback25Count: kotlin.Int? = null,

    /* Number of users who made it through 50% of the video. */
    @Json(name = "playback_50_count")
    val playback50Count: kotlin.Int? = null,

    /* Number of users who made it through 75% of the video. */
    @Json(name = "playback_75_count")
    val playback75Count: kotlin.Int? = null,

    /* Number of users who made it through 100% of the video. */
    @Json(name = "playback_100_count")
    val playback100Count: kotlin.Int? = null

)

