/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AnimatedGifAllOf
import org.openapitools.client.models.Media
import org.openapitools.client.models.VideoAllOfVariants

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param mediaKey The Media Key identifier for this attachment.
 * @param height The height of the media in pixels
 * @param width The width of the media in pixels
 * @param previewImageUrl 
 * @param variants An array of all available variants of the media
 */

data class AnimatedGif (

    @Json(name = "type")
    override val type: kotlin.String,

    /* The Media Key identifier for this attachment. */
    @Json(name = "media_key")
    override val mediaKey: kotlin.String? = null,

    /* The height of the media in pixels */
    @Json(name = "height")
    override val height: kotlin.Int? = null,

    /* The width of the media in pixels */
    @Json(name = "width")
    override val width: kotlin.Int? = null,

    @Json(name = "preview_image_url")
    val previewImageUrl: java.net.URI? = null,

    /* An array of all available variants of the media */
    @Json(name = "variants")
    val variants: kotlin.collections.List<VideoAllOfVariants>? = null

) : Media()

