/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Tweet information of the Tweet being replied to.
 *
 * @param inReplyToTweetId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param excludeReplyUserIds A list of User Ids to be excluded from the reply Tweet.
 */

data class Model2TweetsReply (

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @Json(name = "in_reply_to_tweet_id")
    val inReplyToTweetId: kotlin.String? = null,

    /* A list of User Ids to be excluded from the reply Tweet. */
    @Json(name = "exclude_reply_user_ids")
    val excludeReplyUserIds: kotlin.collections.List<kotlin.String>? = null

)

