/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.OperationalDisconnectProblemAllOf
import org.openapitools.client.models.Problem

import com.squareup.moshi.Json

/**
 * You have been disconnected for operational reasons.
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 * @param disconnectType 
 */

data class OperationalDisconnectProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null,

    @Json(name = "disconnect_type")
    val disconnectType: OperationalDisconnectProblem.DisconnectType? = null

) : Problem() {

    /**
     * 
     *
     * Values: operationalDisconnect,upstreamOperationalDisconnect,forceDisconnect,upstreamUncleanDisconnect,slowReader,internalError,clientApplicationStateDegraded,invalidRules
     */
    enum class DisconnectType(val value: kotlin.String) {
        @Json(name = "OperationalDisconnect") operationalDisconnect("OperationalDisconnect"),
        @Json(name = "UpstreamOperationalDisconnect") upstreamOperationalDisconnect("UpstreamOperationalDisconnect"),
        @Json(name = "ForceDisconnect") forceDisconnect("ForceDisconnect"),
        @Json(name = "UpstreamUncleanDisconnect") upstreamUncleanDisconnect("UpstreamUncleanDisconnect"),
        @Json(name = "SlowReader") slowReader("SlowReader"),
        @Json(name = "InternalError") internalError("InternalError"),
        @Json(name = "ClientApplicationStateDegraded") clientApplicationStateDegraded("ClientApplicationStateDegraded"),
        @Json(name = "InvalidRules") invalidRules("InvalidRules");
    }
}

