/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.PollOption

import com.squareup.moshi.Json

/**
 * Represent a Poll attached to a Tweet
 *
 * @param id Unique identifier of this poll.
 * @param options 
 * @param votingStatus 
 * @param endDatetime 
 * @param durationMinutes 
 */

data class Poll (

    /* Unique identifier of this poll. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "options")
    val options: kotlin.collections.List<PollOption>,

    @Json(name = "voting_status")
    val votingStatus: Poll.VotingStatus? = null,

    @Json(name = "end_datetime")
    val endDatetime: java.time.OffsetDateTime? = null,

    @Json(name = "duration_minutes")
    val durationMinutes: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: `open`,closed
     */
    enum class VotingStatus(val value: kotlin.String) {
        @Json(name = "open") `open`("open"),
        @Json(name = "closed") closed("closed");
    }
}

