/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * An HTTP Problem Details object, as defined in IETF RFC 7807 (https://tools.ietf.org/html/rfc7807).
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 */

interface Problem {

    @Json(name = "type")
    val type: kotlin.String
    @Json(name = "title")
    val title: kotlin.String
    @Json(name = "detail")
    val detail: kotlin.String?
    @Json(name = "status")
    val status: kotlin.Int?
}

