/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.RulesRequestSummary

import com.squareup.moshi.Json

/**
 * 
 *
 * @param sent 
 * @param summary 
 * @param nextToken This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified.
 * @param resultCount Number of Rules in result set
 */

data class RulesResponseMetadata (

    @Json(name = "sent")
    val sent: kotlin.String,

    @Json(name = "summary")
    val summary: RulesRequestSummary? = null,

    /* This parameter is used to get the next 'page' of results. The value used with the parameter is pulled directly from the response provided by the API, and should not be modified. */
    @Json(name = "next_token")
    val nextToken: kotlin.String? = null,

    /* Number of Rules in result set */
    @Json(name = "result_count")
    val resultCount: kotlin.Int? = null

)

