/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * A summary of the results of the addition of user-specified stream filtering rules.
 *
 * @param created Number of user-specified stream filtering rules that were created.
 * @param notCreated Number of user-specified stream filtering rules that were not created.
 * @param valid Number of valid user-specified stream filtering rules.
 * @param invalid Number of invalid user-specified stream filtering rules.
 */

data class RulesRequestSummaryOneOf (

    /* Number of user-specified stream filtering rules that were created. */
    @Json(name = "created")
    val created: kotlin.Int,

    /* Number of user-specified stream filtering rules that were not created. */
    @Json(name = "not_created")
    val notCreated: kotlin.Int,

    /* Number of valid user-specified stream filtering rules. */
    @Json(name = "valid")
    val valid: kotlin.Int,

    /* Number of invalid user-specified stream filtering rules. */
    @Json(name = "invalid")
    val invalid: kotlin.Int

)

