/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * Represent a Search Count Result
 *
 * @param end The end time of the bucket
 * @param start The start time of the bucket
 * @param tweetCount The count for the bucket
 */

data class SearchCount (

    /* The end time of the bucket */
    @Json(name = "end")
    val end: java.time.OffsetDateTime,

    /* The start time of the bucket */
    @Json(name = "start")
    val start: java.time.OffsetDateTime,

    /* The count for the bucket */
    @Json(name = "tweet_count")
    val tweetCount: kotlin.Int

)

