/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Problem
import org.openapitools.client.models.UsageCapExceededProblemAllOf

import com.squareup.moshi.Json

/**
 * A problem that indicates that a usage cap has been exceeded.
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 * @param period 
 * @param scope 
 */

data class UsageCapExceededProblem (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "title")
    override val title: kotlin.String,

    @Json(name = "detail")
    override val detail: kotlin.String? = null,

    @Json(name = "status")
    override val status: kotlin.Int? = null,

    @Json(name = "period")
    val period: UsageCapExceededProblem.Period? = null,

    @Json(name = "scope")
    val scope: UsageCapExceededProblem.Scope? = null

) : Problem() {

    /**
     * 
     *
     * Values: daily,monthly
     */
    enum class Period(val value: kotlin.String) {
        @Json(name = "Daily") daily("Daily"),
        @Json(name = "Monthly") monthly("Monthly");
    }
    /**
     * 
     *
     * Values: account,product
     */
    enum class Scope(val value: kotlin.String) {
        @Json(name = "Account") account("Account"),
        @Json(name = "Product") product("Product");
    }
}

