/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param period 
 * @param scope 
 */

data class UsageCapExceededProblemAllOf (

    @Json(name = "period")
    val period: UsageCapExceededProblemAllOf.Period? = null,

    @Json(name = "scope")
    val scope: UsageCapExceededProblemAllOf.Scope? = null

) {

    /**
     * 
     *
     * Values: daily,monthly
     */
    enum class Period(val value: kotlin.String) {
        @Json(name = "Daily") daily("Daily"),
        @Json(name = "Monthly") monthly("Monthly");
    }
    /**
     * 
     *
     * Values: account,product
     */
    enum class Scope(val value: kotlin.String) {
        @Json(name = "Account") account("Account"),
        @Json(name = "Product") product("Product");
    }
}

