/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.FullTextEntities
import org.openapitools.client.models.UserEntitiesUrl

import com.squareup.moshi.Json

/**
 * A list of metadata found in the user's profile description.
 *
 * @param url 
 * @param description 
 */

data class UserEntities (

    @Json(name = "url")
    val url: UserEntitiesUrl? = null,

    @Json(name = "description")
    val description: FullTextEntities? = null

)

