/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.CashtagFieldsEntity
import fr.haan.openapi_playground_app.data.entities.EntityIndicesInclusiveExclusiveEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param start Index (zero-based) at which position this entity starts.  The index is inclusive.
 * @param end Index (zero-based) at which position this entity ends.  The index is exclusive.
 * @param tag 
 */
@Serializable
data class CashtagEntityEntity (

    /* Index (zero-based) at which position this entity starts.  The index is inclusive. */
    @SerialName(value = "start")
    val start: kotlin.Int,

    /* Index (zero-based) at which position this entity ends.  The index is exclusive. */
    @SerialName(value = "end")
    val end: kotlin.Int,

    @SerialName(value = "tag")
    val tag: kotlin.String

)

