/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.ExpansionsEntity
import fr.haan.openapi_playground_app.data.entities.FilteredStreamingTweetOneOf1Entity
import fr.haan.openapi_playground_app.data.entities.FilteredStreamingTweetOneOfEntity
import fr.haan.openapi_playground_app.data.entities.FilteredStreamingTweetOneOfMatchingRulesEntity
import fr.haan.openapi_playground_app.data.entities.ProblemEntity
import fr.haan.openapi_playground_app.data.entities.TweetEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A tweet or error that can be returned by the streaming tweet API
 *
 * @param `data` 
 * @param matchingRules The list of rules which matched the tweet
 * @param errors 
 * @param includes 
 */
@Serializable
data class FilteredStreamingTweetEntity (

    @SerialName(value = "data")
    val `data`: TweetEntity,

    /* The list of rules which matched the tweet */
    @SerialName(value = "matching_rules")
    val matchingRules: kotlin.collections.List<FilteredStreamingTweetOneOfMatchingRulesEntity>,

    @SerialName(value = "errors")
    val errors: kotlin.collections.List<ProblemEntity>,

    @SerialName(value = "includes")
    val includes: ExpansionsEntity? = null

)

