/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.Model2TweetsGeoEntity
import fr.haan.openapi_playground_app.data.entities.Model2TweetsMediaEntity
import fr.haan.openapi_playground_app.data.entities.Model2TweetsPollEntity
import fr.haan.openapi_playground_app.data.entities.Model2TweetsReplyEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param text The content of the Tweet.
 * @param directMessageDeepLink Link to take the conversation from the public timeline to a private Direct Message.
 * @param quoteTweetId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param forSuperFollowersOnly Exclusive Tweet for super followers.
 * @param reply 
 * @param media 
 * @param poll 
 * @param replySettings Settings to indicate who can reply to the Tweet.
 * @param geo 
 */
@Serializable
data class InlineObject3Entity (

    /* The content of the Tweet. */
    @SerialName(value = "text")
    val text: kotlin.String? = null,

    /* Link to take the conversation from the public timeline to a private Direct Message. */
    @SerialName(value = "direct_message_deep_link")
    val directMessageDeepLink: kotlin.String? = null,

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "quote_tweet_id")
    val quoteTweetId: kotlin.String? = null,

    /* Exclusive Tweet for super followers. */
    @SerialName(value = "for_super_followers_only")
    val forSuperFollowersOnly: kotlin.Boolean? = null,

    @SerialName(value = "reply")
    val reply: Model2TweetsReplyEntity? = null,

    @SerialName(value = "media")
    val media: Model2TweetsMediaEntity? = null,

    @SerialName(value = "poll")
    val poll: Model2TweetsPollEntity? = null,

    /* Settings to indicate who can reply to the Tweet. */
    @SerialName(value = "reply_settings")
    val replySettings: InlineObject3Entity.ReplySettings? = null,

    @SerialName(value = "geo")
    val geo: Model2TweetsGeoEntity? = null

) {

    /**
     * Settings to indicate who can reply to the Tweet.
     *
     * Values: following,mentionedUsers
     */
    @Serializable
    enum class ReplySettings(val value: kotlin.String) {
        @SerialName(value = "following") following("following"),
        @SerialName(value = "mentionedUsers") mentionedUsers("mentionedUsers");
    }
}

