/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A Twitter List is a curated group of accounts.
 *
 * @param id The unique identifier of this List.
 * @param name The name of this List.
 * @param createdAt 
 * @param description 
 * @param followerCount 
 * @param memberCount 
 * @param ownerId Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param `private` 
 */
@Serializable
data class ListEntity (

    /* The unique identifier of this List. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* The name of this List. */
    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "follower_count")
    val followerCount: kotlin.Int? = null,

    @SerialName(value = "member_count")
    val memberCount: kotlin.Int? = null,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "owner_id")
    val ownerId: kotlin.String? = null,

    @SerialName(value = "private")
    val `private`: kotlin.Boolean? = null

)

