/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param disconnectType 
 */
@Serializable
data class OperationalDisconnectProblemAllOfEntity (

    @SerialName(value = "disconnect_type")
    val disconnectType: OperationalDisconnectProblemAllOfEntity.DisconnectType? = null

) {

    /**
     * 
     *
     * Values: operationalDisconnect,upstreamOperationalDisconnect,forceDisconnect,upstreamUncleanDisconnect,slowReader,internalError,clientApplicationStateDegraded,invalidRules
     */
    @Serializable
    enum class DisconnectType(val value: kotlin.String) {
        @SerialName(value = "OperationalDisconnect") operationalDisconnect("OperationalDisconnect"),
        @SerialName(value = "UpstreamOperationalDisconnect") upstreamOperationalDisconnect("UpstreamOperationalDisconnect"),
        @SerialName(value = "ForceDisconnect") forceDisconnect("ForceDisconnect"),
        @SerialName(value = "UpstreamUncleanDisconnect") upstreamUncleanDisconnect("UpstreamUncleanDisconnect"),
        @SerialName(value = "SlowReader") slowReader("SlowReader"),
        @SerialName(value = "InternalError") internalError("InternalError"),
        @SerialName(value = "ClientApplicationStateDegraded") clientApplicationStateDegraded("ClientApplicationStateDegraded"),
        @SerialName(value = "InvalidRules") invalidRules("InvalidRules");
    }
}

