/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `value` 
 * @param parameter 
 * @param section 
 * @param resourceId 
 * @param resourceType 
 */
@Serializable
data class ResourceUnauthorizedProblemAllOfEntity (

    @SerialName(value = "value")
    val `value`: kotlin.String,

    @SerialName(value = "parameter")
    val parameter: kotlin.String,

    @SerialName(value = "section")
    val section: ResourceUnauthorizedProblemAllOfEntity.Section,

    @SerialName(value = "resource_id")
    val resourceId: kotlin.String,

    @SerialName(value = "resource_type")
    val resourceType: ResourceUnauthorizedProblemAllOfEntity.ResourceType

) {

    /**
     * 
     *
     * Values: `data`,includes
     */
    @Serializable
    enum class Section(val value: kotlin.String) {
        @SerialName(value = "data") `data`("data"),
        @SerialName(value = "includes") includes("includes");
    }
    /**
     * 
     *
     * Values: tweet,user,media,list,space
     */
    @Serializable
    enum class ResourceType(val value: kotlin.String) {
        @SerialName(value = "tweet") tweet("tweet"),
        @SerialName(value = "user") user("user"),
        @SerialName(value = "media") media("media"),
        @SerialName(value = "list") list("list"),
        @SerialName(value = "space") space("space");
    }
}

