/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param deleted Number of user-specified stream filtering rules that were deleted.
 * @param notDeleted Number of user-specified stream filtering rules that were not deleted.
 */
@Serializable
data class RulesRequestSummaryOneOf1Entity (

    /* Number of user-specified stream filtering rules that were deleted. */
    @SerialName(value = "deleted")
    val deleted: kotlin.Int,

    /* Number of user-specified stream filtering rules that were not deleted. */
    @SerialName(value = "not_deleted")
    val notDeleted: kotlin.Int

)

