/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.SpaceTopicsEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id The unique identifier of this Space.
 * @param state The current state of the space.
 * @param startedAt When the space was started as a date string
 * @param isTicketed Denotes if the space is a ticketed space
 * @param participantCount The number of participants in a space
 * @param title The title of the space
 * @param hostIds The user ids for the hosts of the space
 * @param updatedAt When the space was last updated
 * @param createdAt Creation time of the space
 * @param creatorId Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param lang The language of the space
 * @param speakerIds An array of user ids for people who were speakers in a space
 * @param invitedUserIds An array of user ids for people who were invited to a space
 * @param scheduledStart A date time stamp for when a space is scheduled to begin
 * @param endedAt End time of the space
 * @param topics The topics of a space, as selected by its creator
 * @param subscriberCount The number of people who have either purchased a ticket or set a reminder for this space.
 */
@Serializable
data class SpaceEntity (

    /* The unique identifier of this Space. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* The current state of the space. */
    @SerialName(value = "state")
    val state: SpaceEntity.State,

    /* When the space was started as a date string */
    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null,

    /* Denotes if the space is a ticketed space */
    @SerialName(value = "is_ticketed")
    val isTicketed: kotlin.Boolean? = null,

    /* The number of participants in a space */
    @SerialName(value = "participant_count")
    val participantCount: kotlin.Int? = null,

    /* The title of the space */
    @SerialName(value = "title")
    val title: kotlin.String? = null,

    /* The user ids for the hosts of the space */
    @SerialName(value = "host_ids")
    val hostIds: kotlin.collections.List<kotlin.String>? = null,

    /* When the space was last updated */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    /* Creation time of the space */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "creator_id")
    val creatorId: kotlin.String? = null,

    /* The language of the space */
    @SerialName(value = "lang")
    val lang: kotlin.String? = null,

    /* An array of user ids for people who were speakers in a space */
    @SerialName(value = "speaker_ids")
    val speakerIds: kotlin.collections.List<kotlin.String>? = null,

    /* An array of user ids for people who were invited to a space */
    @SerialName(value = "invited_user_ids")
    val invitedUserIds: kotlin.collections.List<kotlin.String>? = null,

    /* A date time stamp for when a space is scheduled to begin */
    @Contextual @SerialName(value = "scheduled_start")
    val scheduledStart: java.time.OffsetDateTime? = null,

    /* End time of the space */
    @Contextual @SerialName(value = "ended_at")
    val endedAt: java.time.OffsetDateTime? = null,

    /* The topics of a space, as selected by its creator */
    @SerialName(value = "topics")
    val topics: kotlin.collections.List<SpaceTopicsEntity>? = null,

    /* The number of people who have either purchased a ticket or set a reminder for this space. */
    @SerialName(value = "subscriber_count")
    val subscriberCount: kotlin.Int? = null

) {

    /**
     * The current state of the space.
     *
     * Values: live,scheduled,ended
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "live") live("live"),
        @SerialName(value = "scheduled") scheduled("scheduled"),
        @SerialName(value = "ended") ended("ended");
    }
}

