/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Specifies the type of attachments (if any) present in this Tweet.
 *
 * @param mediaKeys A list of Media Keys for each one of the media attachments (if media are attached).
 * @param pollIds A list of poll IDs (if polls are attached).
 */
@Serializable
data class TweetAttachmentsEntity (

    /* A list of Media Keys for each one of the media attachments (if media are attached). */
    @SerialName(value = "media_keys")
    val mediaKeys: kotlin.collections.List<kotlin.String>? = null,

    /* A list of poll IDs (if polls are attached). */
    @SerialName(value = "poll_ids")
    val pollIds: kotlin.collections.List<kotlin.String>? = null

)

