/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param newestId Most recent Tweet Id returned by search query
 * @param oldestId Oldest Tweet Id returned by search query
 * @param nextToken This value is used to get the next 'page' of results by providing it to the next_token parameter.
 * @param resultCount Number of search query results
 */
@Serializable
data class TweetSearchResponseMetaEntity (

    /* Most recent Tweet Id returned by search query */
    @SerialName(value = "newest_id")
    val newestId: kotlin.String? = null,

    /* Oldest Tweet Id returned by search query */
    @SerialName(value = "oldest_id")
    val oldestId: kotlin.String? = null,

    /* This value is used to get the next 'page' of results by providing it to the next_token parameter. */
    @SerialName(value = "next_token")
    val nextToken: kotlin.String? = null,

    /* Number of search query results */
    @SerialName(value = "result_count")
    val resultCount: kotlin.Int? = null

)

