/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.ContextAnnotationEntity
import fr.haan.openapi_playground_app.data.entities.FullTextEntitiesEntity
import fr.haan.openapi_playground_app.data.entities.ReplySettingsEntity
import fr.haan.openapi_playground_app.data.entities.TweetAttachmentsEntity
import fr.haan.openapi_playground_app.data.entities.TweetGeoEntity
import fr.haan.openapi_playground_app.data.entities.TweetNonPublicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.TweetOrganicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.TweetPromotedMetricsEntity
import fr.haan.openapi_playground_app.data.entities.TweetPublicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.TweetReferencedTweetsEntity
import fr.haan.openapi_playground_app.data.entities.TweetWithheldEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param text The content of the Tweet.
 * @param createdAt Creation time of the Tweet.
 * @param authorId Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param inReplyToUserId Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param conversationId Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
 * @param replySettings 
 * @param referencedTweets A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent.
 * @param attachments 
 * @param contextAnnotations 
 * @param withheld 
 * @param geo 
 * @param entities 
 * @param publicMetrics 
 * @param possiblySensitive Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences.
 * @param lang Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag.
 * @param source The name of the app the user Tweeted from.
 * @param nonPublicMetrics 
 * @param promotedMetrics 
 * @param organicMetrics 
 */
@Serializable
data class TweetEntity (

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "id")
    val id: kotlin.String,

    /* The content of the Tweet. */
    @SerialName(value = "text")
    val text: kotlin.String,

    /* Creation time of the Tweet. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "author_id")
    val authorId: kotlin.String? = null,

    /* Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "in_reply_to_user_id")
    val inReplyToUserId: kotlin.String? = null,

    /* Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers. */
    @SerialName(value = "conversation_id")
    val conversationId: kotlin.String? = null,

    @Contextual @SerialName(value = "reply_settings")
    val replySettings: ReplySettingsEntity? = null,

    /* A list of Tweets this Tweet refers to. For example, if the parent Tweet is a Retweet, a Quoted Tweet or a Reply, it will include the related Tweet referenced to by its parent. */
    @SerialName(value = "referenced_tweets")
    val referencedTweets: kotlin.collections.List<TweetReferencedTweetsEntity>? = null,

    @SerialName(value = "attachments")
    val attachments: TweetAttachmentsEntity? = null,

    @SerialName(value = "context_annotations")
    val contextAnnotations: kotlin.collections.List<ContextAnnotationEntity>? = null,

    @SerialName(value = "withheld")
    val withheld: TweetWithheldEntity? = null,

    @SerialName(value = "geo")
    val geo: TweetGeoEntity? = null,

    @SerialName(value = "entities")
    val entities: FullTextEntitiesEntity? = null,

    @SerialName(value = "public_metrics")
    val publicMetrics: TweetPublicMetricsEntity? = null,

    /* Indicates if this Tweet contains URLs marked as sensitive, for example content suitable for mature audiences. */
    @SerialName(value = "possibly_sensitive")
    val possiblySensitive: kotlin.Boolean? = null,

    /* Language of the Tweet, if detected by Twitter. Returned as a BCP47 language tag. */
    @SerialName(value = "lang")
    val lang: kotlin.String? = null,

    /* The name of the app the user Tweeted from. */
    @SerialName(value = "source")
    val source: kotlin.String? = null,

    @SerialName(value = "non_public_metrics")
    val nonPublicMetrics: TweetNonPublicMetricsEntity? = null,

    @SerialName(value = "promoted_metrics")
    val promotedMetrics: TweetPromotedMetricsEntity? = null,

    @SerialName(value = "organic_metrics")
    val organicMetrics: TweetOrganicMetricsEntity? = null

)

