/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.PointEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The location tagged on the Tweet, if the user provided one.
 *
 * @param coordinates 
 * @param placeId The identifier for this place
 */
@Serializable
data class TweetGeoEntity (

    @SerialName(value = "coordinates")
    val coordinates: PointEntity? = null,

    /* The identifier for this place */
    @SerialName(value = "place_id")
    val placeId: kotlin.String? = null

)

