/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param nextToken This value is used to get the next 'page' of results by providing it to the next_token parameter.
 * @param totalTweetCount Sum of search query count results
 */
@Serializable
data class TweetCountsResponseMetaEntity (

    /* This value is used to get the next 'page' of results by providing it to the next_token parameter. */
    @SerialName(value = "next_token")
    val nextToken: kotlin.String? = null,

    /* Sum of search query count results */
    @SerialName(value = "total_tweet_count")
    val totalTweetCount: kotlin.Int? = null

)

