/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.ProblemEntity
import fr.haan.openapi_playground_app.data.entities.UsageCapExceededProblemAllOfEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A problem that indicates that a usage cap has been exceeded.
 *
 * @param type 
 * @param title 
 * @param detail 
 * @param status 
 * @param period 
 * @param scope 
 */
@Serializable
data class UsageCapExceededProblemEntity (

    @SerialName(value = "type")
    override val type: kotlin.String,

    @SerialName(value = "title")
    override val title: kotlin.String,

    @SerialName(value = "detail")
    override val detail: kotlin.String? = null,

    @SerialName(value = "status")
    override val status: kotlin.Int? = null,

    @SerialName(value = "period")
    val period: UsageCapExceededProblemEntity.Period? = null,

    @SerialName(value = "scope")
    val scope: UsageCapExceededProblemEntity.Scope? = null

) : ProblemEntity() {

    /**
     * 
     *
     * Values: daily,monthly
     */
    @Serializable
    enum class Period(val value: kotlin.String) {
        @SerialName(value = "Daily") daily("Daily"),
        @SerialName(value = "Monthly") monthly("Monthly");
    }
    /**
     * 
     *
     * Values: account,product
     */
    @Serializable
    enum class Scope(val value: kotlin.String) {
        @SerialName(value = "Account") account("Account"),
        @SerialName(value = "Product") product("Product");
    }
}

