/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param period 
 * @param scope 
 */
@Serializable
data class UsageCapExceededProblemAllOfEntity (

    @SerialName(value = "period")
    val period: UsageCapExceededProblemAllOfEntity.Period? = null,

    @SerialName(value = "scope")
    val scope: UsageCapExceededProblemAllOfEntity.Scope? = null

) {

    /**
     * 
     *
     * Values: daily,monthly
     */
    @Serializable
    enum class Period(val value: kotlin.String) {
        @SerialName(value = "Daily") daily("Daily"),
        @SerialName(value = "Monthly") monthly("Monthly");
    }
    /**
     * 
     *
     * Values: account,product
     */
    @Serializable
    enum class Scope(val value: kotlin.String) {
        @SerialName(value = "Account") account("Account"),
        @SerialName(value = "Product") product("Product");
    }
}

