/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities

import fr.haan.openapi_playground_app.data.entities.MediaEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfNonPublicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfOrganicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfPromotedMetricsEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfPublicMetricsEntity
import fr.haan.openapi_playground_app.data.entities.VideoAllOfVariantsEntity

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param type 
 * @param mediaKey The Media Key identifier for this attachment.
 * @param height The height of the media in pixels
 * @param width The width of the media in pixels
 * @param previewImageUrl 
 * @param durationMs 
 * @param variants An array of all available variants of the media
 * @param publicMetrics 
 * @param nonPublicMetrics 
 * @param organicMetrics 
 * @param promotedMetrics 
 */
@Serializable
data class VideoEntity (

    @SerialName(value = "type")
    override val type: kotlin.String,

    /* The Media Key identifier for this attachment. */
    @SerialName(value = "media_key")
    override val mediaKey: kotlin.String? = null,

    /* The height of the media in pixels */
    @SerialName(value = "height")
    override val height: kotlin.Int? = null,

    /* The width of the media in pixels */
    @SerialName(value = "width")
    override val width: kotlin.Int? = null,

    @Contextual @SerialName(value = "preview_image_url")
    val previewImageUrl: java.net.URI? = null,

    @SerialName(value = "duration_ms")
    val durationMs: kotlin.Int? = null,

    /* An array of all available variants of the media */
    @SerialName(value = "variants")
    val variants: kotlin.collections.List<VideoAllOfVariantsEntity>? = null,

    @SerialName(value = "public_metrics")
    val publicMetrics: VideoAllOfPublicMetricsEntity? = null,

    @SerialName(value = "non_public_metrics")
    val nonPublicMetrics: VideoAllOfNonPublicMetricsEntity? = null,

    @SerialName(value = "organic_metrics")
    val organicMetrics: VideoAllOfOrganicMetricsEntity? = null,

    @SerialName(value = "promoted_metrics")
    val promotedMetrics: VideoAllOfPromotedMetricsEntity? = null

) : MediaEntity

