/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fr.haan.openapi_playground_app.data.entities


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bitRate The bit rate of the media
 * @param contentType The content type of the media
 * @param url The url to the media
 */
@Serializable
data class VideoAllOfVariantsEntity (

    /* The bit rate of the media */
    @SerialName(value = "bit_rate")
    val bitRate: kotlin.Int? = null,

    /* The content type of the media */
    @SerialName(value = "content_type")
    val contentType: kotlin.String? = null,

    /* The url to the media */
    @Contextual @SerialName(value = "url")
    val url: java.net.URI? = null

)

