/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.42
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import java.io.IOException

import org.openapitools.client.models.AddBookmarkRequest
import org.openapitools.client.models.BookmarkMutationResponse
import org.openapitools.client.models.Error
import org.openapitools.client.models.GenericTweetsTimelineResponse
import org.openapitools.client.models.Problem

import com.squareup.moshi.Json

import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.Success
import org.openapitools.client.infrastructure.toMultiValue

class BookmarksApi(basePath: kotlin.String = defaultBasePath) : ApiClient(basePath) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.twitter.com")
        }
    }

    /**
     * enum for parameter expansions
     */
     enum class Expansions_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "author_id") authorId("author_id"),
         @Json(name = "referenced_tweets.id") referencedTweetsPeriodId("referenced_tweets.id"),
         @Json(name = "in_reply_to_user_id") inReplyToUserId("in_reply_to_user_id"),
         @Json(name = "geo.place_id") geoPeriodPlaceId("geo.place_id"),
         @Json(name = "attachments.media_keys") attachmentsPeriodMediaKeys("attachments.media_keys"),
         @Json(name = "attachments.poll_ids") attachmentsPeriodPollIds("attachments.poll_ids"),
         @Json(name = "entities.mentions.username") entitiesPeriodMentionsPeriodUsername("entities.mentions.username"),
         @Json(name = "referenced_tweets.id.author_id") referencedTweetsPeriodIdPeriodAuthorId("referenced_tweets.id.author_id"),
         ;
     }

    /**
     * enum for parameter tweetFields
     */
     enum class TweetFields_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "id") id("id"),
         @Json(name = "created_at") createdAt("created_at"),
         @Json(name = "text") text("text"),
         @Json(name = "author_id") authorId("author_id"),
         @Json(name = "in_reply_to_user_id") inReplyToUserId("in_reply_to_user_id"),
         @Json(name = "referenced_tweets") referencedTweets("referenced_tweets"),
         @Json(name = "attachments") attachments("attachments"),
         @Json(name = "withheld") withheld("withheld"),
         @Json(name = "geo") geo("geo"),
         @Json(name = "entities") entities("entities"),
         @Json(name = "public_metrics") publicMetrics("public_metrics"),
         @Json(name = "possibly_sensitive") possiblySensitive("possibly_sensitive"),
         @Json(name = "source") source("source"),
         @Json(name = "lang") lang("lang"),
         @Json(name = "context_annotations") contextAnnotations("context_annotations"),
         @Json(name = "non_public_metrics") nonPublicMetrics("non_public_metrics"),
         @Json(name = "promoted_metrics") promotedMetrics("promoted_metrics"),
         @Json(name = "organic_metrics") organicMetrics("organic_metrics"),
         @Json(name = "conversation_id") conversationId("conversation_id"),
         @Json(name = "reply_settings") replySettings("reply_settings"),
         ;
     }

    /**
     * enum for parameter userFields
     */
     enum class UserFields_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "id") id("id"),
         @Json(name = "created_at") createdAt("created_at"),
         @Json(name = "name") name("name"),
         @Json(name = "username") username("username"),
         @Json(name = "protected") `protected`("protected"),
         @Json(name = "verified") verified("verified"),
         @Json(name = "withheld") withheld("withheld"),
         @Json(name = "profile_image_url") profileImageUrl("profile_image_url"),
         @Json(name = "location") location("location"),
         @Json(name = "url") url("url"),
         @Json(name = "description") description("description"),
         @Json(name = "entities") entities("entities"),
         @Json(name = "pinned_tweet_id") pinnedTweetId("pinned_tweet_id"),
         @Json(name = "public_metrics") publicMetrics("public_metrics"),
         ;
     }

    /**
     * enum for parameter mediaFields
     */
     enum class MediaFields_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "media_key") mediaKey("media_key"),
         @Json(name = "duration_ms") durationMs("duration_ms"),
         @Json(name = "height") height("height"),
         @Json(name = "preview_image_url") previewImageUrl("preview_image_url"),
         @Json(name = "type") type("type"),
         @Json(name = "url") url("url"),
         @Json(name = "width") width("width"),
         @Json(name = "public_metrics") publicMetrics("public_metrics"),
         @Json(name = "non_public_metrics") nonPublicMetrics("non_public_metrics"),
         @Json(name = "organic_metrics") organicMetrics("organic_metrics"),
         @Json(name = "promoted_metrics") promotedMetrics("promoted_metrics"),
         @Json(name = "alt_text") altText("alt_text"),
         @Json(name = "variants") variants("variants"),
         ;
     }

    /**
     * enum for parameter placeFields
     */
     enum class PlaceFields_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "id") id("id"),
         @Json(name = "name") name("name"),
         @Json(name = "country_code") countryCode("country_code"),
         @Json(name = "place_type") placeType("place_type"),
         @Json(name = "full_name") fullName("full_name"),
         @Json(name = "country") country("country"),
         @Json(name = "contained_within") containedWithin("contained_within"),
         @Json(name = "geo") geo("geo"),
         ;
     }

    /**
     * enum for parameter pollFields
     */
     enum class PollFields_getUsersIdBookmarks(val value: kotlin.String) {
         @Json(name = "id") id("id"),
         @Json(name = "options") options("options"),
         @Json(name = "voting_status") votingStatus("voting_status"),
         @Json(name = "end_datetime") endDatetime("end_datetime"),
         @Json(name = "duration_minutes") durationMinutes("duration_minutes"),
         ;
     }

    /**
    * Bookmarks by User
    * Returns Tweet objects that have been bookmarked by the requesting user
    * @param id The ID of the user for whom to return results 
    * @param maxResults The maximum number of results (optional)
    * @param paginationToken This parameter is used to get the next &#39;page&#39; of results. (optional)
    * @param expansions A comma separated list of fields to expand. (optional)
    * @param tweetFields A comma separated list of Tweet fields to display. (optional)
    * @param userFields A comma separated list of User fields to display. (optional)
    * @param mediaFields A comma separated list of Media fields to display. (optional)
    * @param placeFields A comma separated list of Place fields to display. (optional)
    * @param pollFields A comma separated list of Poll fields to display. (optional)
    * @return GenericTweetsTimelineResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getUsersIdBookmarks(id: kotlin.String, maxResults: kotlin.Int?, paginationToken: kotlin.String?, expansions: kotlin.collections.List<Expansions_getUsersIdBookmarks>?, tweetFields: kotlin.collections.List<TweetFields_getUsersIdBookmarks>?, userFields: kotlin.collections.List<UserFields_getUsersIdBookmarks>?, mediaFields: kotlin.collections.List<MediaFields_getUsersIdBookmarks>?, placeFields: kotlin.collections.List<PlaceFields_getUsersIdBookmarks>?, pollFields: kotlin.collections.List<PollFields_getUsersIdBookmarks>?) : GenericTweetsTimelineResponse {
        val localVarResponse = getUsersIdBookmarksWithHttpInfo(id = id, maxResults = maxResults, paginationToken = paginationToken, expansions = expansions, tweetFields = tweetFields, userFields = userFields, mediaFields = mediaFields, placeFields = placeFields, pollFields = pollFields)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GenericTweetsTimelineResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Bookmarks by User
    * Returns Tweet objects that have been bookmarked by the requesting user
    * @param id The ID of the user for whom to return results 
    * @param maxResults The maximum number of results (optional)
    * @param paginationToken This parameter is used to get the next &#39;page&#39; of results. (optional)
    * @param expansions A comma separated list of fields to expand. (optional)
    * @param tweetFields A comma separated list of Tweet fields to display. (optional)
    * @param userFields A comma separated list of User fields to display. (optional)
    * @param mediaFields A comma separated list of Media fields to display. (optional)
    * @param placeFields A comma separated list of Place fields to display. (optional)
    * @param pollFields A comma separated list of Poll fields to display. (optional)
    * @return ApiResponse<GenericTweetsTimelineResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getUsersIdBookmarksWithHttpInfo(id: kotlin.String, maxResults: kotlin.Int?, paginationToken: kotlin.String?, expansions: kotlin.collections.List<Expansions_getUsersIdBookmarks>?, tweetFields: kotlin.collections.List<TweetFields_getUsersIdBookmarks>?, userFields: kotlin.collections.List<UserFields_getUsersIdBookmarks>?, mediaFields: kotlin.collections.List<MediaFields_getUsersIdBookmarks>?, placeFields: kotlin.collections.List<PlaceFields_getUsersIdBookmarks>?, pollFields: kotlin.collections.List<PollFields_getUsersIdBookmarks>?) : ApiResponse<GenericTweetsTimelineResponse?> {
        val localVariableConfig = getUsersIdBookmarksRequestConfig(id = id, maxResults = maxResults, paginationToken = paginationToken, expansions = expansions, tweetFields = tweetFields, userFields = userFields, mediaFields = mediaFields, placeFields = placeFields, pollFields = pollFields)

        return request<Unit, GenericTweetsTimelineResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation getUsersIdBookmarks
    *
    * @param id The ID of the user for whom to return results 
    * @param maxResults The maximum number of results (optional)
    * @param paginationToken This parameter is used to get the next &#39;page&#39; of results. (optional)
    * @param expansions A comma separated list of fields to expand. (optional)
    * @param tweetFields A comma separated list of Tweet fields to display. (optional)
    * @param userFields A comma separated list of User fields to display. (optional)
    * @param mediaFields A comma separated list of Media fields to display. (optional)
    * @param placeFields A comma separated list of Place fields to display. (optional)
    * @param pollFields A comma separated list of Poll fields to display. (optional)
    * @return RequestConfig
    */
    fun getUsersIdBookmarksRequestConfig(id: kotlin.String, maxResults: kotlin.Int?, paginationToken: kotlin.String?, expansions: kotlin.collections.List<Expansions_getUsersIdBookmarks>?, tweetFields: kotlin.collections.List<TweetFields_getUsersIdBookmarks>?, userFields: kotlin.collections.List<UserFields_getUsersIdBookmarks>?, mediaFields: kotlin.collections.List<MediaFields_getUsersIdBookmarks>?, placeFields: kotlin.collections.List<PlaceFields_getUsersIdBookmarks>?, pollFields: kotlin.collections.List<PollFields_getUsersIdBookmarks>?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (maxResults != null) {
                    put("max_results", listOf(maxResults.toString()))
                }
                if (paginationToken != null) {
                    put("pagination_token", listOf(paginationToken.toString()))
                }
                if (expansions != null) {
                    put("expansions", toMultiValue(expansions.toList(), "csv"))
                }
                if (tweetFields != null) {
                    put("tweet.fields", toMultiValue(tweetFields.toList(), "csv"))
                }
                if (userFields != null) {
                    put("user.fields", toMultiValue(userFields.toList(), "csv"))
                }
                if (mediaFields != null) {
                    put("media.fields", toMultiValue(mediaFields.toList(), "csv"))
                }
                if (placeFields != null) {
                    put("place.fields", toMultiValue(placeFields.toList(), "csv"))
                }
                if (pollFields != null) {
                    put("poll.fields", toMultiValue(pollFields.toList(), "csv"))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/2/users/{id}/bookmarks".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Add Tweet to Bookmarks
    * Adds a Tweet (ID in the body) to the requesting user&#39;s (in the path) bookmarks
    * @param id The ID of the user for whom to add bookmarks 
    * @param addBookmarkRequest  
    * @return BookmarkMutationResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun postUsersIdBookmarks(id: kotlin.String, addBookmarkRequest: AddBookmarkRequest) : BookmarkMutationResponse {
        val localVarResponse = postUsersIdBookmarksWithHttpInfo(id = id, addBookmarkRequest = addBookmarkRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BookmarkMutationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Add Tweet to Bookmarks
    * Adds a Tweet (ID in the body) to the requesting user&#39;s (in the path) bookmarks
    * @param id The ID of the user for whom to add bookmarks 
    * @param addBookmarkRequest  
    * @return ApiResponse<BookmarkMutationResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun postUsersIdBookmarksWithHttpInfo(id: kotlin.String, addBookmarkRequest: AddBookmarkRequest) : ApiResponse<BookmarkMutationResponse?> {
        val localVariableConfig = postUsersIdBookmarksRequestConfig(id = id, addBookmarkRequest = addBookmarkRequest)

        return request<AddBookmarkRequest, BookmarkMutationResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation postUsersIdBookmarks
    *
    * @param id The ID of the user for whom to add bookmarks 
    * @param addBookmarkRequest  
    * @return RequestConfig
    */
    fun postUsersIdBookmarksRequestConfig(id: kotlin.String, addBookmarkRequest: AddBookmarkRequest) : RequestConfig<AddBookmarkRequest> {
        val localVariableBody = addBookmarkRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/2/users/{id}/bookmarks".replace("{"+"id"+"}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

    /**
    * Remove a bookmarked Tweet
    * Removes a Tweet from the requesting user&#39;s bookmarked Tweets.
    * @param id The ID of the user whose bookmark is to be removed. 
    * @param tweetId The ID of the tweet that the user is removing from bookmarks 
    * @return BookmarkMutationResponse
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    * @throws UnsupportedOperationException If the API returns an informational or redirection response
    * @throws ClientException If the API returns a client error response
    * @throws ServerException If the API returns a server error response
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun usersIdBookmarksDelete(id: kotlin.String, tweetId: kotlin.String) : BookmarkMutationResponse {
        val localVarResponse = usersIdBookmarksDeleteWithHttpInfo(id = id, tweetId = tweetId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as BookmarkMutationResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
    * Remove a bookmarked Tweet
    * Removes a Tweet from the requesting user&#39;s bookmarked Tweets.
    * @param id The ID of the user whose bookmark is to be removed. 
    * @param tweetId The ID of the tweet that the user is removing from bookmarks 
    * @return ApiResponse<BookmarkMutationResponse?>
    * @throws IllegalStateException If the request is not correctly configured
    * @throws IOException Rethrows the OkHttp execute method exception
    */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun usersIdBookmarksDeleteWithHttpInfo(id: kotlin.String, tweetId: kotlin.String) : ApiResponse<BookmarkMutationResponse?> {
        val localVariableConfig = usersIdBookmarksDeleteRequestConfig(id = id, tweetId = tweetId)

        return request<Unit, BookmarkMutationResponse>(
            localVariableConfig
        )
    }

    /**
    * To obtain the request config of the operation usersIdBookmarksDelete
    *
    * @param id The ID of the user whose bookmark is to be removed. 
    * @param tweetId The ID of the tweet that the user is removing from bookmarks 
    * @return RequestConfig
    */
    fun usersIdBookmarksDeleteRequestConfig(id: kotlin.String, tweetId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json, application/problem+json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/2/users/{id}/bookmarks/{tweet_id}".replace("{"+"id"+"}", "$id").replace("{"+"tweet_id"+"}", "$tweetId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            body = localVariableBody
        )
    }

}
